language: elixir
elixir:
  - 1.4
otp_release:
  - 19.3
  - 18.3
env:
  - CACHE_ENABLED=true
  - CACHE_ENABLED=true TEST_OPTS='--exclude redis_pubsub --include phoenix_pubsub --no-start' PUBSUB_BROKER=phoenix_pubsub
  - CACHE_ENABLED=false TEST_OPTS='--only integration'
services:
  - redis-server
script:
  - mix test --force $TEST_OPTS
notifications:
  email:
    on_success: never
    on_failure: never
